### ISSUE TITLE
Timeout error about POST request

### ISSUE THREAD

**Issue by zhangzhanhui** [analyticsinmotion/create-images-with-dall-e-in-microsoft-word#2]
Hi, there

I'm sure I can draw with dall-e with other tools. But I encountered timeout error about POST request.
I have no idea about the reason.

How can I solve the problem?

Thank you for your contribution!

Jarvis

**Comment by rossarmstrong** [comment]
Hi @zhangzhanhui, thank you for submitting your issue. The issue you have raised typically occurs when ChatGPT is at capacity and its servers cannot respond your request in time. The best thing to do after that is wait a minute and try your request again.

**Comment by rossarmstrong** [comment]
This issue has been addressed and the case will be closed.
